vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
env_prefix = "Jenkins-Master"
my_ip = "yourIP"
instance_type = "t2.micro"
ami_name = "ubuntu/images/hvm-ssd/ubuntu-jammy-*-amd64-server-*"
public_key_location = "/home/userid/.ssh/id_rsa.pub"
